// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdacvgunqboxgrjuhcyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkYWN2Z3VucWJveGdyanVoY3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTIyMDEsImV4cCI6MjA3MTA2ODIwMX0.6LnV217l-gPNKOMuZDkhOaW2qAUMGc3Xw6VaBPVhtL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});